### ISSUE TITLE
TODO: 待汉化文本

### ISSUE THREAD

**Issue by Ricky-fight** [ShaBaiTianCN/FTB-Inferno#35]
1. want_not.snbt  
![image](https://user-images.githubusercontent.com/13982778/206653980-d02d387e-ffbe-4c39-83b6-e2260094c331.png)
![image](https://user-images.githubusercontent.com/13982778/206653863-1aae3872-d69c-4323-a71f-66b9e62c708f.png)
2. sanguine_sting.snbt 
![image](https://user-images.githubusercontent.com/13982778/206654185-563ce503-c3df-4bd0-b4c9-504a5f121eb2.png)
![image](https://user-images.githubusercontent.com/13982778/206654208-ce09212e-d959-4ad5-bae8-0ba976255e47.png)
![image](https://user-images.githubusercontent.com/13982778/206654273-9668e2b1-6904-4c80-bc02-b4bf904d14eb.png)
3. want_not.snbt
![image](https://user-images.githubusercontent.com/13982778/206654685-cfcebd1f-d664-4009-8bbf-7d1aad79b25c.png)
4. kubejs\client_scripts\info.js 91- 99行 '制作一个Bellringer Gateway Pearl，召唤敲钟人并打败它来获得其掉落物。'

**Comment by AnzhiZhang** [comment]
这些是因为模组没翻译？科技模组可以找紫菜
