### ISSUE TITLE
任务不能完成

### ISSUE THREAD

**Issue by EnterFor** [ShaBaiTianCN/FTB-Inferno#41]
刚开始的   燧石稿任务，做了两个都不提示完成，不知道是不是汉化出了问题。
![image](https://user-images.githubusercontent.com/10114685/207653327-b3bbabda-937a-455d-8004-e0a4c37b2cac.png)
![image](https://user-images.githubusercontent.com/10114685/207653384-650919c8-7aa7-4173-bd6f-0dc82fb0cbb1.png)

**Comment by AnzhiZhang** [comment]
是整合包bug，建议开编辑模式手动解锁

**Comment by EnterFor** [comment]
我就是这么干的，所以关闭了此问题，谢谢你能回答我，ღ( ´･ᴗ･` )比心
